FreelanceWebApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('', include('message.urls')),
    path('', include('project.urls')),
    path('', include('payment.urls')),
    path('',include('restapi.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'project'
urlpatterns = [
    path('project/', views.project, name="project"),
    path('project/<int:project_id>', views.details, name="details"),
    url(r'^results/$', views.search, name="search"),
    path('project/create/', views.create, name = "create"),
    path('project/delete/<int:pk>', views.delete, name="delete"),
    path('project/edit/<int:project_id>', views.update, name="update"),
    path('project/bids/<int:project_id>', views.bids, name="bids"),
    path('project/add-bids/<int:project_id>', views.add_bids, name="add_bids"),   
]

user/urls.py
from django.urls import path, include
from . import views

app_name = 'user'
urlpatterns = [
    path("login/", views.user_login, name="login"),
    path("logout/", views.user_logout, name="logout"),
    path("register/", views.register, name="register"),
    path("view-profile/<int:pk>/", views.view_profile, name="view_profile"),
    path("edit-profile/<int:pk>/", views.edit_profile, name="edit_profile"),
    path("delete-profile/<int:pk>/", views.delete_profile, name="delete_profile"),
    path("funds/", views.add_funds, name="add_funds"),
]

project/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Project(models.Model):
    project_id = models.AutoField(primary_key=True)
    project_title = models.CharField(max_length=100)
    project_description = models.TextField()
    availability_status = models.BooleanField(default=True)
    project_type = models.CharField(max_length=30)
    project_time = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.project_title

class Bid(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    bid_status = models.BooleanField(default=True)
    bid_time = models.DateTimeField(auto_now_add=True)
    

project/forms.py
from django import forms
from project.models import Project

class Form(forms.ModelForm):
    class Meta:
        model = Project
        fields = ('project_title', 'project_description', 'project_type')

class updateForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ('project_title', 'project_description', 'project_type','availability_status')

project/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse, HttpResponseNotFound, Http404
from django.db.models import Q
from django.contrib import messages
from project.forms import Form, updateForm
from user.models import AppUser
from .models import Project, Bid
from .decorators import authenticated_user
from project.paginations import pagination

# Create your views here.

@authenticated_user   
def project(request):

    template = "project/project.html"
    object_list = Project.objects.filter(availability_status__contains=1).order_by('-project_time')#latest projects are shown according to the latest time

    pages = pagination(request, object_list, 2)

    context={
        'items': pages[0],
        'page_range': pages[1],
        'nbar': 'project',
    }
    return render(request, template, context)

# viewing the project
@authenticated_user
def details(request, project_id):#project id is passed
    template = "project/details.html"
    try:
        details = Project.objects.get(pk=project_id)
    except Project.DoesNotExist:
        raise Http404("Project does not exist.")# if project doesnot exist it throws http error
    context = {
        'details': details,
        'nbar': 'project',
    }
    return render(request, template, context)

@authenticated_user
def search(request):
    template = "project/project.html"
    query = request.GET.get('q')
    if query:
        results = Project.objects.filter(Q(project_title__icontains=query) | Q(project_description__icontains=query) | Q(project_type__icontains=query))
    else:# if not authenticated he/she is redirected to welcome page
        results = Project.objects.filter(availability_status__contains=1)
    pages = pagination(request, results, 1)
    context = {
        'items': pages[0],
        'page_range': pages[1],
        'query': query,
        'nbar': 'project',
    }
    return render(request, template, context)

@authenticated_user
def create(request):
    if request.method == "POST":
        create_form = Form(request.POST)
        if create_form.is_valid():
            cform = create_form.save(commit=False)
            cform.user = request.user
            cform.save()
            messages.success(request, f'Post successfully created!')
            return redirect('project:project')
    else:
        create_form = Form()
    context={
        "create_form": create_form
    }
    return render(request, 'project/create.html', context)

# editing the existing project
@authenticated_user
def update(request, project_id):
    project_obj = Project.objects.get(pk=project_id)
    uid = request.user.id
    pid = project_obj.user_id#if user id matches with project id then update page is shown
    if uid == pid:
        post_data = request.POST or None
        uForm = updateForm(post_data, instance = project_obj) 
        if uForm.is_valid():
            uForm.save()
            messages.success(request, f'Post updated.')# message displayed by redirecting on the project page
            return redirect('project:details', project_id=project_id)
        context={
            "uForm": uForm,
        }
        return render(request, 'project/update.html', context)
    else:# else it redirects to the projects page
        messages.warning(request, f'Cannot edit this post')
        return redirect('project:project')

# Deleting a project
@authenticated_user
def delete(request,pk):# Gets id of the project to be deleted
    project_obj = Project.objects.get(pk = pk)
    uid = request.user.id
    user = request.user
    pid = project_obj.user_id
    if uid == pid or user.is_superuser:# if user id and and project id matches then the project is deleted
        project_obj.delete()
        messages.success(request, f'Post has been deleted.')
        return redirect('project:project')
    else:# message is displayed if the condition does not match
        messages.warning(request, f'Cannot delete this post')
        return redirect('project:project')

@authenticated_user
def bids(request, project_id):
    template = "project/bids.html"
    try:
        bids = Bid.objects.filter(bid_status__contains=1).order_by('-bid_time')
        project_obj = Project.objects.get(pk = project_id)
    except Project.DoesNotExist:
        raise Http404("Project does not exist.")
    context = {
        'bids': bids,
        'project':project_obj,
        'nbar': 'project',
    }
    return render(request, template, context)

def add_bids(request, project_id):
    project_obj = Project.objects.get(pk = project_id)
    uid = request.user.id
    pid = project_obj.project_id
    b = Bid.objects.create(project_id=pid, user_id=uid)
    b.save()
    messages.success(request, f'You have applied for this project. Please wait while the person reviews the biddings.')
    return redirect('project:project')

project/templates/project/bids.html
{% extends "base.html" %}

{% block content %}
<title>Bids Received</title>

<a href="/project" class="btn btn-light btn-sm mb-4">Go Back</a>

{% for b in bids %}
{% if b.project_id == project.project_id %}
<legend style="font-size: large;"><a href="{% url 'user:view_profile' b.user.id %}">{{b.user}}</a> applied for {{project.project_title}} project</legend>
<hr>
{% endif %}
{% empty %}
<hr>
<legend>You have no bids</legend>
<hr>
{% endfor %}
{% endblock %}

project/templates/project/create.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}

<div class="content-section">
	<a href="../" class="btn btn-light btn-sm mb-4">Go Back</a>
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Create Post</legend>
            {{ create_form|crispy }}
            <button type="submit" class="btn btn-outline-info">Post</button>
        </fieldset>
    </form>
</div>

{% endblock %}

project/templates/project/details.html
{% extends "base.html" %}

{% block content %}
<title>Project Details</title>

<a href="/project" class="btn btn-light btn-sm mb-4">Go Back</a>
<h1>{{details.project_title}}</h1>
<div>
	{{details.project_description}}
</div>
<hr>
<small>Written on {{details.project_time}} by <a href="{% url 'user:view_profile' details.user_id %}"> {{details.user}} </a></small>
<hr>

{% if details.user == user or request.user.is_superuser %}
{% if details.user == user %}
<a href="edit/{{details.project_id}}"><button class="btn btn-primary float-left mr-3">Edit</button></a>
<a href="bids/{{details.project_id}}"><button class="btn btn-primary float-left">Bids</button></a>
{% endif %}
<form action="{% url 'project:delete' details.pk %}" action="POST">
	{% csrf_token %}
	<button class="btn btn-danger float-right">Delete</button>
</form>
{% else %}
<a href="add-bids/{{details.project_id}}"><button class="btn btn-success float-right run">Apply for this
		Project</button></a>
{% endif %}

{% endblock %}

project/templates/project/pagination.html
{% if items.has_other_pages %}
<div class="text-center">
    <div class="offset-5 text-center pagination">
        <nav>
            <ul class="pagination" style="justify-content: center;">
                {% if items.has_previous %}
                    <li class="page-item"><a href="?page={{ items.previous_page_number }}{% if query %}&q={{query}}{% endif %}" class="page-link">&laquo;</a></li>
                {% else %}
                    <li class="page-item disabled"><a href="#" class="page-link">&laquo;</a></li>
                {% endif %}
                {% for i in page_range %}
                    {% if items.number == i %}
                        <li class="page-item active"><a class="page-link" href="#">{{ i }}</a></li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="?page={{ i }}{% if query %}&q={{query}}{% endif %}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if items.has_next %}
                    <li class="page-item"><a href="?page={{ items.next_page_number }}{% if query %}&q={{query}}{% endif %}" class="page-link">&raquo;</a></li>
                {% else %}
                    <li class="page-item disabled"><a href="#" class="page-link">&raquo;</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div>
{% endif %}

project/templates/project/project.html
{% extends "base.html" %}

{% block content %}

<title>Project</title>

<div class="row">
    <div class="col-md-8">
        <a href="{% url 'project:create' %}" class="btn btn-primary btn-sm mb-3">Create Post</a>
        {% for p in items %}
        <div class="card">
            <div class="card-body">
                <a href="{% url 'project:details' p.project_id %}">
                    <h5 class="card-title">{{p.project_title}}</h5>
                </a>
                <h6 class="card-subtitle mb-2 text-muted">{{p.project_time}}</h6>
                <p class="card-text">{{p.project_description}}</p>
            </div>
        </div>
        <br>
        {% empty %}
        <div class="card">
            <div class="card-header">
                Projects
            </div>
            <div class="card-body">
                <h5 class="card-title">No posts available!</h5>
                <p class="card-text">No projects are available for now to work on, meanwhile you can create one!</p>
            </div>
        </div>
        <br>
        {% endfor %}

        {% include 'project/pagination.html' %}
    </div>
    {% include 'project/search.html' %}
</div>

{% endblock %}

project/templates/project/search.html
<div class="col-md-4">
    <div class="content-section">
        <h4>Search</h4>
        <p class='text-muted'>Search Projects From Here...</p>
            <ul class="list-group">
                <li class="list-group-item list-group-item-light">
                    <form action="{% url 'project:search' %}" method="GET" class="form-inline text-right">
                        <div class="form-group">
                            <input name="q" value="{{ request.GET.q }}" class="form-control form-control-sm" type="text" placeholder="Search...">
                            <button class="btn btn-light btn-sm" type="submit" style="margin-top: 0px;">Search</button>
                        </div>
                    </form>
                </li>
            </ul>
    </div>
</div>

project/templates/project/update.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}

<title>Update Project</title>
<a href="../{{ project.project_id }}" class="btn btn-light btn-sm mb-4">Go Back</a>
<form method="POST">
    {% csrf_token %}
       {{ uForm | crispy }}
        <button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>
{% endblock %}