FreelanceWebApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('', include('message.urls')),
    path('', include('project.urls')),
    path('', include('payment.urls')),
    path('',include('restapi.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

message/urls.py
from django.urls import path
from . import views

app_name = "message"
urlpatterns = [
    path('', views.welcome, name="welcome"),
    path('message/', views.new_message, name="new_message"),
    path('message/<int:pk>/', views.message, name="message"),
    path('message/<int:pk>/save/',views.create_message, name="create_message"),
]

payment/urls.py
from django.urls import path
from . import views

app_name = "payment"
urlpatterns = [
    path('payment/<int:id>/',views.payment,name="payment"),
    path('view-payment/',views.view_payments,name="view_payments"),
]

project/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'project'
urlpatterns = [
    path('project/', views.project, name="project"),
    path('project/<int:project_id>', views.details, name="details"),
    url(r'^results/$', views.search, name="search"),
    path('project/create/', views.create, name = "create"),
    path('project/delete/<int:pk>', views.delete, name="delete"),
    path('project/edit/<int:project_id>', views.update, name="update"),
    path('project/bids/<int:project_id>', views.bids, name="bids"),
    path('project/add-bids/<int:project_id>', views.add_bids, name="add_bids"),   
]

user/urls.py
from django.urls import path, include
from . import views

app_name = 'user'
urlpatterns = [
    path("login/", views.user_login, name="login"),
    path("logout/", views.user_logout, name="logout"),
    path("register/", views.register, name="register"),
    path("view-profile/<int:pk>/", views.view_profile, name="view_profile"),
    path("edit-profile/<int:pk>/", views.edit_profile, name="edit_profile"),
    path("delete-profile/<int:pk>/", views.delete_profile, name="delete_profile"),
    path("funds/", views.add_funds, name="add_funds"),
]

user/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class AppUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.IntegerField()
    cv = models.FileField(upload_to='cv', null=True, blank=True)
    funds = models.IntegerField(blank=True,null=True,default=0)

user/forms.py
from django import forms
from user.models import AppUser
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    email = forms.EmailField(required=True)
    password = forms.CharField(widget = forms.PasswordInput)
    confirm_password = forms.CharField(widget = forms.PasswordInput)
    class Meta:
        model = User
        fields = ['first_name', 'last_name','username','email','password']
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
            return user

class EditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name','username','email']

class ProfileForm(forms.ModelForm):
    class Meta:
        model = AppUser
        fields = ['phone', 'cv']

user/views.py
# importing required packages
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from .forms import UserForm, ProfileForm, EditForm
from django.contrib import messages
from project.decorators import unauthenticated_user, authenticated_user
from django.contrib.auth.models import User
from .models import AppUser
from project.models import Project
from project.paginations import pagination

# Create your views here.
# takes required data from user and register it to database
@unauthenticated_user
def register(request):
    if request.method == "POST":
        user_form = UserForm(request.POST)
        # check if the form is valid
        profile_form = ProfileForm(request.POST,request.FILES)
        if user_form.is_valid() and profile_form.is_valid() and user_form.cleaned_data['password'] == user_form.cleaned_data['confirm_password']:
            user = user_form.save()
            appuser = profile_form.save(commit=False)
            appuser.user = user
            appuser.save()
            username = user_form.cleaned_data.get('username')
            login(request, user)
            messages.success(request, f'Account created successfully for { username }!')
            return redirect('project:project')
        elif user_form.data['password'] != user_form.data['confirm_password']:
            messages.warning(request, f'The password does not match.')
    else:
        user_form = UserForm()
        profile_form = ProfileForm()

    context={
        "user_form": user_form,
        "profile_form": profile_form
    }
    return render(request, "user/register.html", context)

# it logouts the user and redirect to welcome page
def user_logout(request):
    logout(request)
    return redirect('message:welcome')

# it logs user in if valid
@unauthenticated_user
def user_login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, f'You are logged in as { username }!')
                return redirect('project:project')
        else:
            return render(request, 'user/login.html', context={"form": form})

    form = AuthenticationForm()
    return render(request, 'user/login.html', context={"form": form})

@authenticated_user
def view_profile(request, pk):
    detail = User.objects.get(pk=pk)
    if detail.is_superuser:
        other = None
    else:
        other = AppUser.objects.get(user_id=pk)
    object_list = Project.objects.filter(user_id=pk).order_by('-project_time')#latest projects are shown according to the latest time
    pages = pagination(request, object_list, 2)
    context = {
        "detail":detail,
        "other":other,
        'items': pages[0],
        'page_range': pages[1],
        "nbar":"profile"
    }
    return render(request,'user/view_profile.html',context)

@authenticated_user
def edit_profile(request, pk):
    post_data = request.POST or None
    file_data = request.FILES or None
    app_user = AppUser.objects.get(user=request.user)
    user_form = EditForm(post_data, instance=request.user)
    profile_form = ProfileForm(post_data,file_data, instance=app_user)
    if user_form.is_valid() and profile_form.is_valid():
        user_form.save()
        profile_form.save()
        return redirect("user:view_profile", pk=request.user.id)

    context={
        "user_form": user_form,
        "profile_form": profile_form
    }
    return render(request, 'user/edit_profile.html',context)

@authenticated_user
def delete_profile(request,pk):
    main = User.objects.get(pk = pk)
    uid = request.user.id
    pid = main.id
    if uid == pid:
        main.delete()
        logout(request)
        messages.success(request, f'User has been deleted')
        return redirect('user:register')
    elif request.user.is_superuser:
        main.delete()
        messages.success(request, f'User has been deleted')
        return redirect('message:welcome')
    else:
        messages.warning(request, f'You cannot perform the following action!')
        return redirect('user:view_profile', pk = uid)

def add_funds(request):
    previous_funds = AppUser.objects.get(user=request.user).funds
    if request.method == "POST":
        funds = int(request.POST['fund'])
        funds = funds + previous_funds
        AppUser.objects.filter(user=request.user).update(funds=funds)
        return redirect('user:view_profile', pk=request.user.id)
    return render(request, "user/add_funds.html")

user/templates/user/add_funds.html
{% extends "base.html" %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <input type="text"  name="fund" placeholder="Enter Amount">
    <button type="submit" class=" btn btn-primary">Add Amount </button>
</form>
{% endblock %}

user/templates/user/edit_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-row">
      <div class="form-group col-md-6 mb-0">
        {{ user_form.first_name|as_crispy_field }}
      </div>
      <div class="form-group col-md-6 mb-0">
        {{ user_form.last_name|as_crispy_field }}
      </div>
    </div>
    {{ user_form.username|as_crispy_field }}
    {{ user_form.email|as_crispy_field }}
    {{ profile_form|crispy }}
    <button type="submit" class=" btn btn-primary"> Update Profile </button>
</form>
{% endblock %}

user/templates/user/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<title>Login</title>

<div class="content-seciton">
    <form method="POST" class="form-text">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Log In</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-froup">
            <button type="Submit" class="btn btn-outline-info mb-4">Login</button>
        </div>
    </form>
    <div class="border-top pt-3" style="padding-bottom: 25px">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{% url 'user:register' %}">Sign Up Now</a>
        </small>
    </div>
</div>

{% endblock %}

user/templates/user/register.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}

<div class="content-section">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Register</legend>
            {{ user_form|crispy }}
            {{ profile_form|crispy }}
            <button type="submit" class="btn btn-outline-info">Sign Up</button>
        </fieldset>
    </form>
    <div class="border-top pt-3 linksignin">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="{% url 'user:login' %}">Sign In</a>
        </small>
    </div>
</div>

{% endblock %}

user/templates/user/view_profile.html
{% extends 'base.html' %}

{% block title %}
View Profile
{% endblock %}

{% block content %}
<h1 class="text-center">Profile</h1>

<hr>
<div class="row mb-5">
    <div class="col-md-4">
        <div class="card" style="width: 18rem;">
            <img src="https://www.windstream.com/getmedia/b2e4e38a-7cb6-4ca9-9544-54dfeaca6304/icon_user-circle.png.aspx?width=1520&height=980&ext=.png"
                class="card-img-top" alt="img">
            <div class="card-body" style="margin-bottom: -20px;">
                <h5 class="card-title">{{ detail }}</h5>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Firstname: {{ detail.first_name }}</li>
                <li class="list-group-item">Lastname: {{ detail.last_name }}</li>
                <li class="list-group-item">Email: {{ detail.email }}</li>
                <li class="list-group-item">Phone: {{ other.phone }}</li>
                {% if other.cv == "" %}
                <li class="list-group-item">CV: <a href="#"><legend style="font-size: medium;">No CV Found</legend></a></li>
                {% else %}
                <li class="list-group-item">CV:<a href="{{other.cv.url}}" download class="btn btn-primary btn-sm ml-3">Download CV</a></li>
                {% endif %}
                {% if not request.user.is_superuser %}
                {% if request.user.id == detail.id %}
                    <li class="list-group-item"> Balance : {{other.funds}}</li>
                    <li class="list-group-item"><a href="{% url 'user:add_funds' %}"><button class="btn btn-primary btn-sm">Add Funds</button></a>
                    <a href="{% url 'payment:view_payments' %}"><button class="btn btn-primary btn-sm">View Payment</button></a></li>
                {% else %}
                    <li class="list-group-item"><a href="{% url 'payment:payment' detail.id %}"><button class="btn btn-primary">Pay</button></a>
                    <a href="{% url 'message:message' detail.id %}"><button class="btn btn-primary">Message</button></a></li>
                {% endif %}
                {% endif %}
            </ul>

            {% if request.user.id == detail.id or request.user.is_superuser %}
                <div class="container">
                {% if request.user.id == detail.id %}
                    <a href="{% url 'user:edit_profile' user.pk %}"><button class="btn btn-primary btn-sm float-left mr-2"> Edit Profile</button></a>
                {% endif %}
                    <form method="POST" enctype="multipart/form-data" action="{% url 'user:delete_profile' detail.pk %}">
                        {% csrf_token %}
                        <button class="btn btn-danger btn-sm float-left" type="submit"> Delete Profile </button>
                    </form>
                </div>
            {% endif %}
        </div>
    </div>
    <div class="col-md-8">
        <a href="{% url 'project:create' %}" class="btn btn-primary btn-sm float-right mb-3">Create Post</a>
        <legend>Projects:</legend>
        <div class="clearfix"></div>
        {% for p in items %}
        <div class="card">
            <div class="card-body">
                <a href="{% url 'project:details' p.project_id %}">
                    <h5 class="card-title">{{p.project_title}}</h5>
                </a>
                <h6 class="card-subtitle mb-2 text-muted">{{p.project_time}}</h6>
                <p class="card-text">{{p.project_description}}</p>
            </div>
        </div>
        <br>
        {% empty %}
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">No Posts</h5>
                <p class="card-text">You have not created any posts!</p>
            </div>
        </div>
        <br>
        {% endfor %}
        {% include 'project/pagination.html' %}
    </div>
</div>
{% endblock %}