FreelanceWebApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('', include('message.urls')),
    path('', include('project.urls')),
    path('', include('payment.urls')),
    path('',include('restapi.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

message/urls.py
from django.urls import path
from . import views

app_name = "message"
urlpatterns = [
    path('', views.welcome, name="welcome"),
    path('message/', views.new_message, name="new_message"),
    path('message/<int:pk>/', views.message, name="message"),
    path('message/<int:pk>/save/',views.create_message, name="create_message"),
]

user/urls.py
from django.urls import path, include
from . import views

app_name = 'user'
urlpatterns = [
    path("login/", views.user_login, name="login"),
    path("logout/", views.user_logout, name="logout"),
    path("register/", views.register, name="register"),
    path("view-profile/<int:pk>/", views.view_profile, name="view_profile"),
    path("edit-profile/<int:pk>/", views.edit_profile, name="edit_profile"),
    path("delete-profile/<int:pk>/", views.delete_profile, name="delete_profile"),
    path("funds/", views.add_funds, name="add_funds"),
]

message/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Message(models.Model):
    message = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='messages_sent')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='messages_received')

message/views.py
from django.shortcuts import render, redirect
from project.decorators import authenticated_user
from django.contrib.auth.models import User
from .models import Message

# Create your views here.

def welcome(request):
    return render(request, 'message/welcome.html')

#The following function helps to create a new chat room and to start a message
@authenticated_user
def new_message(request):
    Users = User.objects.all()
    return render(request, "new_message.html", context={'Users':Users, 'nbar': 'message'})

#This function is used to display the message in the chat room
@authenticated_user
def message(request, pk):
    detail = User.objects.get(pk = pk)
    message = Message.objects.all()
    return render(request, "message.html", context={'message':message, 'detail':detail, 'nbar': 'message'})

#This function is used while storing the message in the database
@authenticated_user
def create_message(request, pk):
    user = User.objects.get(pk=pk)
    if request.method == "POST":
        message = request.POST['message'] #This takes the message written in the input message box
        rid = user.id #It takes the id of the user that is being watched by the current user 
        sid = request.user.id #This takes the id of the current logged in user to store in the database
        msg = Message.objects.create(message=message, receiver_id=rid, sender_id=sid)
        msg.save()
    return redirect('message:message', pk=pk)

message/templates/message.html
{% extends "base.html" %}

{% block content %}

<title>Message</title>

<div class="chat-page">
    <div class="msg-inbox">
        <div class="chats">
            <div class="msg-page">
                {% for msg in message %}
                    {% if request.user.id == msg.sender.id and detail.id == msg.receiver.id or request.user.id == msg.receiver.id and detail.id == msg.sender.id %}
                        {% if msg.sender.id == request.user.id %}
                            <div class="outgoing-chats">
                                <div class="outgoing-chats-label">
                                    <a href="{% url 'user:view_profile' msg.sender.id %}">{{msg.sender}}:</a>
                                </div>
                                <div class="outgoing-chats-msg">
                                    <p>{{msg.message}}</p>
                                    <span class="time">{{msg.created}}</span>
                                </div>
                            </div>                    
                        {% else %} 
                            <div class="received-chats">
                                <div class="received-chats-label">
                                    <a href="{% url 'user:view_profile' msg.sender.id %}">{{msg.sender}}:</a>
                                </div>
                                <div class="received-msg">
                                    <div class="received-msg-inbox">
                                        <p>{{msg.message}}</p>
                                        <span class="time">{{msg.created}}</span>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    {% else %}
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>

    <form method="POST" action="{% url 'message:create_message' detail.id %}" class="message-input">
        {% csrf_token %}
        <div class="form-group">
            <input type="text" class="form-control float-left" name="message" style="max-width: 1000px;">
            <button type="submit" class="btn btn-primary float-right" style="margin-right: 75px;">Submit</button>
        </div>
    </form>

    <script>
        $(".msg-page").scrollTop($(".msg-page")[0].scrollHeight);
    </script>

{% endblock %}

message/templates/new_message.html
{% extends "base.html" %}

{% block content %}

<title>Message</title>

    <div class="card-body">
        <h4 class="card-title">Start Messaging</h4>
        {% for u in Users %} <!-- It loops through the Users stored in database and displays them on the page -->
        {% if u == request.user %} <!-- It checks the current user and displays all other users besides the current user -->
        {% else %} 
            <ul class="list-group">
                <li class="list-group-item"><a href="{% url 'message:message' u.id %}">{{u}}</a></li>
            </ul>
        {% endif %}
        {% endfor %}
    </div>

{% endblock %}