FreelanceWebApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('', include('message.urls')),
    path('', include('project.urls')),
    path('', include('payment.urls')),
    path('',include('restapi.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

message/urls.py
from django.urls import path
from . import views

app_name = "message"
urlpatterns = [
    path('', views.welcome, name="welcome"),
    path('message/', views.new_message, name="new_message"),
    path('message/<int:pk>/', views.message, name="message"),
    path('message/<int:pk>/save/',views.create_message, name="create_message"),
]

project/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'project'
urlpatterns = [
    path('project/', views.project, name="project"),
    path('project/<int:project_id>', views.details, name="details"),
    url(r'^results/$', views.search, name="search"),
    path('project/create/', views.create, name = "create"),
    path('project/delete/<int:pk>', views.delete, name="delete"),
    path('project/edit/<int:project_id>', views.update, name="update"),
    path('project/bids/<int:project_id>', views.bids, name="bids"),
    path('project/add-bids/<int:project_id>', views.add_bids, name="add_bids"),   
]

user/urls.py
from django.urls import path, include
from . import views

app_name = 'user'
urlpatterns = [
    path("login/", views.user_login, name="login"),
    path("logout/", views.user_logout, name="logout"),
    path("register/", views.register, name="register"),
    path("view-profile/<int:pk>/", views.view_profile, name="view_profile"),
    path("edit-profile/<int:pk>/", views.edit_profile, name="edit_profile"),
    path("delete-profile/<int:pk>/", views.delete_profile, name="delete_profile"),
    path("funds/", views.add_funds, name="add_funds"),
]

message/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Message(models.Model):
    message = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='messages_sent')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='messages_received')

message/views.py
from django.shortcuts import render, redirect
from project.decorators import authenticated_user
from django.contrib.auth.models import User
from .models import Message

# Create your views here.

def welcome(request):
    return render(request, 'message/welcome.html')

#The following function helps to create a new chat room and to start a message
@authenticated_user
def new_message(request):
    Users = User.objects.all()
    return render(request, "new_message.html", context={'Users':Users, 'nbar': 'message'})

#This function is used to display the message in the chat room
@authenticated_user
def message(request, pk):
    detail = User.objects.get(pk = pk)
    message = Message.objects.all()
    return render(request, "message.html", context={'message':message, 'detail':detail, 'nbar': 'message'})

#This function is used while storing the message in the database
@authenticated_user
def create_message(request, pk):
    user = User.objects.get(pk=pk)
    if request.method == "POST":
        message = request.POST['message'] #This takes the message written in the input message box
        rid = user.id #It takes the id of the user that is being watched by the current user 
        sid = request.user.id #This takes the id of the current logged in user to store in the database
        msg = Message.objects.create(message=message, receiver_id=rid, sender_id=sid)
        msg.save()
    return redirect('message:message', pk=pk)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>
    {% include "navbar.html" %}
    <div class="container">
        {% include "messages.html" %}
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

templates/messages.html
{% if messages %}
    {% for m in messages %}
        <div class="alert alert-{{ m.tags }}">
            {{ m }}
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark shadow-sm p-sm-3 mb-3">
    <a class="navbar-brand" href="/">
        Freelancer
    </a>
    <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li>
                    <a class="nav-link {% if nbar == 'project' %}active{% endif %}" href="{% url 'project:project' %}">Project</a>
                </li>
                <li>
                    <a class="nav-link {% if nbar == 'message' %}active{% endif %}" href="{% url 'message:new_message' %}">Message</a>
                </li>
                <li>
                    <a class="nav-link {% if nbar == 'profile' %}active{% endif %}" href="{% url 'user:view_profile' user.id %}">Profile</a>
                </li>
                <li>
                    <a class="nav-link" href="{% url 'user:logout' %}">Logout</a>
                </li>
            {% else %}
                <li>
                    <a class="nav-link {% if nbar == 'login' %}active{% endif %}" href="../login">Login</a>
                </li>
                <li>
                    <a class="nav-link {% if nbar == 'register' %}active{% endif %}" href="../register">Register</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>